### ISSUE TITLE
overly rigid treatment of top nodes in SMATCH

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#12]
when comparing our (forthcoming) MCES scorer with SMATCH, it emerged that there is a difference in the count of correct tuples for two test AMRs from the SMATCH distribution:
```
# ::snt The boy is a hard worker.
(p / person
      :domain (b / boy)
      :ARG0-of (w / work-01
            :manner (h / hard)))
```
```
# ::snt The boy is a hard worker.
(w / worker
      :mod (h / hard)
      :domain (b / boy))
```
SMATCH correctly establishes three node correspondences: the ‘b’ and ‘h’ nodes from both graphs, and ‘p’ from the first graph with ‘w’ from the second.  on this view, the two graphs have the same top node, share two node labels (‘boy’ and ‘hard’), as well as one edge (:domain).  however, SMATCH appears to represent the top properties as triples that include the node label, which results in an undesirable double penalty.  i wonder whether this treatment in SMATCH is background to the critique by [Anchieta et al. (2019)](https://arxiv.org/abs/1905.12069)?

**Comment by danielhers** [comment]
At least according to the example in the [smatch paper](https://amr.isi.edu/smatch-13.pdf), the top triple is not part of the scoring... but it seems ‘attribute’ triples (including top) were probably just introduced later.

**Comment by oepen** [comment]
closing this issue in mtool (for now), since we decided we wanted to maintain compatibility with the ‘official’ version of SMATCH.
