### ISSUE TITLE
rename ‘properties’ on Edge class to ‘attributes’

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#14]
for ease of reference, i would like to limit ‘properties’ for nodes and rather talk about edge ‘attributes’.

**Comment by oepen** [comment]
this was a little all over the place, but hopefully worth it down the road!  because the renaming also affects the MRP serialization (for UCCA only), i have bumped the MRP file format version to 1.0 (and made the MRP input coded robust to either the old or new format).  still, we need to alert participants to this change and possibly even re-issue at least the UCCA training graphs?

**Comment by danielhers** [comment]
How about supporting both options when reading?

**Comment by oepen** [comment]
the MRP input codec currently will look for ‘attributes’ first, then for ‘properties’.  so we do support both, i would say.

but we now have updates to AMR (#29), EDS (#4), and UCCA—i am beginning to lean towards a re-release of the training data.

to be discussed later today.
