### ISSUE TITLE
respect node ordering in bi-lexical graphs

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#15]
the MCES search so far is uninformed by the total ordering relation that holds on nodes in SDP graphs.  i believe it should not explore correspondences p = q where there exist nodes i and j with previously established correspondences, such that i < p but j > q.

**Comment by khlmnn** [comment]
Just to make sure I understand this – we (implicitly) assume that the order of the nodes in SDP graphs is given by their position in graph.nodes. In particular, there is no explicit node property for the linear position. Correct?

On 16 Jun 2019, at 03:21, Stephan Oepen <notifications@github.com<mailto:notifications@github.com>> wrote:


the MCES search so far is uninformed by the total ordering relation that holds on nodes in SDP graphs. i believe it should not explore correspondences p = q where there exist nodes i and j with previously established correspondences, such that i < p but j > q.

**Comment by oepen** [comment]
the MRP graph representation has a top-level property ‘flavor’, which should have a value of 0 for bilexical graphs.  i would be prepared to require of our participants that they set that value correctly.
