### ISSUE TITLE
parallelize scoring

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#16]
seeing as the MCES (and SMATCH) metrics can be compuationally expensive to compute, it could be tempting to score individual gold–system pairs in parallel (presumably using multi-processing, because of GIL).  this should be straightforward, in principle, but we might have to give a little though to global state: both MCES and SMATCH currently have some global variables.

**Comment by foxik** [comment]
BTW, for internal purposes I have implemented a trivial parallelization of mces computation. I have no desire to get this code in mtool, I am sharing it just for fun.

```python
def mrp_score(gold, system, rrhc, mces, parallelize=1):
    assert gold and system

    if parallelize <= 1:
        return mtool.score.mces.evaluate(gold, system, format="json", limits={"rrhc": rrhc, "mces": mces})
    else:
        import multiprocessing.pool
        import time

        start = time.time()
        with multiprocessing.pool.Pool(parallelize) as pool:
            scores = pool.starmap(mrp_score, [([g], [s], rrhc, mces) for g, s in mtool.score.core.intersect(gold, system)], 1)

        score = {"time": time.time() - start}
        if scores:
            for k in scores[0]:
                if isinstance(scores[0][k], int):
                    score[k] = sum(s[k] for s in scores)
                elif isinstance(scores[0][k], dict):
                    assert set(scores[0][k].keys()) == {"g", "s", "c", "p", "r", "f"}
                    score[k] = {i: sum(s[k][i] for s in scores) for i in ["g", "s", "c"]}
                    score[k].update({i: v for i, v in zip(["p", "r", "f"], mtool.score.core.fscore(score[k]["g"], score[k]["s"], score[k]["c"]))})
                else:
                    raise ValueError("Unknown score type {}".format(type(scores[0][k])))

        return score
```

**Comment by oepen** [comment]
thanks, milan!  something in a very similar spirit is now part of the ‘dev’ branch.  we would be grateful if you or others would give it a shot over the next few days, as we are preparing to merge it back into the official code base for the task.  the new argument is `--cores`, where a value of `0` will greedily try to use all available cores on the local machine.
