### ISSUE TITLE
Do we need to predict node values in SDP?

### ISSUE THREAD

**Issue by wangxinyu0922** [cfmrp/mtool#18]
As the properties in SDP are fixed to be ['pos','frame'] pair, so do we need to predict the corresponding values? As we can get "pos" value from companion data, we only need "frame"?

**Comment by oepen** [comment]
yes, both PoS and frame predictions will be scored, each as a node property in its own right.  note, however, that not all nodes have frame values in PSD (essentially only verbs do, where the PSD frame values are in fact sense identifiers into the CzEngVallex dictionary).

**Comment by wangxinyu0922** [comment]
![图片](https://user-images.githubusercontent.com/17926734/59827384-200cbc00-936b-11e9-9cd5-4e43bf925a9d.png)
Hi, is this table that the what we need to predict in evaluation? For example, we don't need to predict node properties in EDS.

**Comment by oepen** [comment]
thanks for catching this one: the table was wrong in this respect!  inasmuch as there are node properties in EDS, they will be scored in MRP evaluation.  for MRP, we have in some cases dropped information from the original graph banks, for example :wiki links in AMR, implicit (unexpressed nodes) in UCCA, and _most_ EDS node properties (things like tense and number).  however, as you point out there are remaining node properties in EDS, notably the CARG in named entities, and that is certainly relevant for MRP parsers to predict.
