### ISSUE TITLE
activate order-dependent properties in analyzer

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#21]
```
./main.py --read mrp data/sample/dm/wsj.mrp --analyze
```

**Comment by khlmnn** [comment]
Sorry to be a bit slow here, but how would we know whether a given MRP file should be interpreted as ‘ordered’, and where would we find the relevant information (position of nodes)?

On 16 Jun 2019, at 18:37, Stephan Oepen <notifications@github.com<mailto:notifications@github.com>> wrote:


./main.py --read mrp data/sample/dm/wsj.mrp --analyze

**Comment by oepen** [comment]
i would look to the top-level ‘flavor’ and/or ‘framework’ properties.  for bi-lexical graphs, the ‘nodes’ list is ordered.

**Comment by khlmnn** [comment]
Okay, but how do we handle MRP files containing graphs with different flavors? Is it okay to update order-related properties only for those graphs for which flavor == 0?

**Comment by oepen** [comment]
the idea had not occurred to me that one could mix graphs of different flavors or frameworks in a single file :-).  i could imagine we just outlaw that!  for example discard any graphs that diverge on these properties from the first entry in the file?
