### ISSUE TITLE
quality control of UCCA scorer

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#32]
i just added the robust comparison of anchors to the UCCA scorer (now as sets of character positions), and in doing so also stumbled into (and fixed) a bug in yield computation.  the good news is that we now seem able to consider the anchoring in the attachment as equivalent (for 'Even though').  daniel, just in case you wonder about the tupa output: i post-edited it, to create a test case.

however, i am left thinking we should validate the character-based UCCA scores in mtool better.  could you run the native UCCA scorer on some of our test cases and compare the actual counts?
```
./main.py --read mrp --score ucca --gold data/score/ucca/anchors.gold.mrp data/score/ucca/anchors.tupa.mrp
{"n": 1,
 "labeled": {"primary": {"g": 6, "s": 6, "c": 6, "p": 1.0, "r": 1.0, "f": 1.0},
             "remote": {"g": 0, "s": 0, "c": 0, "p": 0.0, "r": 0.0, "f": 0.0}},
 "unlabeled": {"primary": {"g": 6, "s": 6, "c": 6, "p": 1.0, "r": 1.0, "f": 1.0},
               "remote": {"g": 0, "s": 0, "c": 0, "p": 0.0, "r": 0.0, "f": 0.0}}}
```

[gold.pdf](https://github.com/cfmrp/mtool/files/3307286/gold.pdf)
[tupa.pdf](https://github.com/cfmrp/mtool/files/3307288/tupa.pdf)

**Comment by oepen** [comment]
i am running out of debugging time for today, but i was expecting the MCES "edges" counts to correspond to the "labeled" counts from the UCCA scorer.  the sums of gold and system edges seem to match, but it is almost as if MCES manages to establish a node correspondence such that two additional edges match, even though their UCCA yields (projections of anchoring) differ.  now, is that a desirable outcome, or not?
```
./main.py --read mrp --score ucca --gold data/score/ucca/test.gold.mrp data/score/ucca/test.tupa.mrp 
{"n": 1,
 "labeled": {"primary": {"g": 16, "s": 13, "c": 6, "p": 0.46153846153846156, "r": 0.375, "f": 0.41379310344827586},
 "remote": {"g": 1, "s": 0, "c": 0, "p": 0.0, "r": 0.0, "f": 0.0}},
 "unlabeled": {"primary": {"g": 15, "s": 13, "c": 9, "p": 0.6923076923076923, "r": 0.6, "f": 0.6428571428571429},
 "remote": {"g": 1, "s": 0, "c": 0, "p": 0.0, "r": 0.0, "f": 0.0}}}
```
```
./main.py --read mrp --score mrp --gold data/score/ucca/test.gold.mrp data/score/ucca/test.tupa.mrp 
{"n": 1,
 "tops": {"g": 1, "s": 1, "c": 1, "p": 1.0, "r": 1.0, "f": 1.0},
 "labels": {"g": 0, "s": 0, "c": 0, "p": 0.0, "r": 0.0, "f": 0.0},
 "properties": {"g": 0, "s": 0, "c": 0, "p": 0.0, "r": 0.0, "f": 0.0},
 "anchors": {"g": 9, "s": 9, "c": 7, "p": 0.7777777777777778, "r": 0.7777777777777778, "f": 0.7777777777777778},
 "edges": {"g": 17, "s": 13, "c": 8, "p": 0.6153846153846154, "r": 0.47058823529411764, "f": 0.5333333333333333},
 "attributes": {"g": 1, "s": 0, "c": 0, "p": 0.0, "r": 0.0, "f": 0.0},
 "all": {"g": 28, "s": 23, "c": 16, "p": 0.6956521739130435, "r": 0.5714285714285714, "f": 0.6274509803921569}}
```

**Comment by omriabnd** [comment]
I don't think it's a desirable outcome, but I see the value in using a
uniform evaluation measure across different schemes. I think if we report
this score along with the standard UCCA F-score that'll be fine.

**Comment by oepen** [comment]
with the new structural constraints, i re-ran this comparison and still get a higher edge match from the MCES search than from the native UCCA scorer.  tracing the node-to-node correspondences in the two graphs, the result does look plausible to me, although i am not sure yet which is the additional edge.  following is how gold nodes correspond to system nodes:
```
[(0, 0), (1, 1), (2, 2), (3, 3), (4, -1), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 4), (11, 10), (12, 11), (13, 12), (14, -1), (15, 13)]
```
[gold.pdf](https://github.com/cfmrp/mtool/files/3322549/gold.pdf)
[tupa.pdf](https://github.com/cfmrp/mtool/files/3322550/tupa.pdf)

**Comment by danielhers** [comment]
I think it's desirable. In the native UCCA scorer we don't score the anchoring edges themselves, so penalizing this C edge would be the only way to penalize "my daughter" not being a unit.

**Comment by omriabnd** [comment]
I think it's reasonable for this example. I'm mostly worried about the high degree of symmetry that you have given that we don't have that many edge label types in UCCA, which may lead to completely unrelated edges being matched. However, maybe this concern doesn't happen much in practice (maybe because our trees are not that deep, so you're never too far from the anchoring edges, not sure). 
In any event, as I said I think it makes sense to use a uniform measure for all schemes, so we can go with this one, but we should also report the native UCCA measure.
