### ISSUE TITLE
read (and record) UCCA graphs in order

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#33]
my impression is that `get_passages_with_progress_bar()` does not preserve the order of graphs from the input file (which at times makes debugging harder and has led to our MRP data releases being unordered).  neither of these are real problems, but for convenience i would be tempted to try and deterministically preserve the oder of UCCA graphs from the XML files.  i see there is a variant `get_passages()`, which might also eliminate our module dependency on TQDM.  could we just use that as an alternative?

**Comment by danielhers** [comment]
It actually preserves the order; the problem is that `read()` in `ucca.py` saves the full paths in a `set`.
I really don't mind using `get_passages()` instead, though. It's entirely the same except that there's no progress bar. And then we can remove the dependence on `tqdm`.

**Comment by oepen** [comment]
ah, thanks!  quite possibly i was the one who originally used { ... } in that function reading in the file names.
