### ISSUE TITLE
MRP to UCCA write codec

### ISSUE THREAD

**Issue by danielhers** [cfmrp/mtool#35]
`codec/ucca.py` currently allows converting UCCA XML files to the MRP format, but not the other way around. Adding the reverse conversion will allow

- Training the TUPA baseline (and any other UCCA parser) on all MRP data (#2)
- Applying the UCCA scorer to MRP data (#32)
- Round-trip conversion for evaluation and testing of the conversion

**Comment by wangxinyu0922** [comment]
Hi, when will reverse conversion (MRP to UCCA XML format) be available?

**Comment by oepen** [comment]
over time, we want all mtool converters to be bidirectional, but this is no priority.  there ismots more to do that is directly needed for the 2019 shared, so bidrectional codecs may not come until after the evaluation phase.

**Comment by JZXXX** [comment]
When I converted UCCA XML files to the MRP format, some files succeeded, but some failed with reporting '' 'Linkage' object has no attribute 'start_position' ''. All of the files come from the English Wiki corpus (https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-Wiki), with passages being split into sentences. The converted files are: 
[test-id-sentence.zip](https://github.com/cfmrp/mtool/files/3344425/test-id-sentence.zip). I can't find the reason, thanks!

**Comment by DreamerDeo** [comment]
@JZXXX  Could you tell me how to convert UCCA XML files (English-Wiki) to the MRP format. I want to compare my model with TUPA on this dataset. 
In **data/sample/ucca**, I found that the wsj.ids and wsj.txt is required, while the original UCCA Wiki Corpus doesn't provide those resource.

**Comment by danielhers** [comment]
@DreamerDeo as said on https://github.com/cfmrp/mtool/issues/45, you are not allowed to use UCCA data available on GitHub for developing your parser. This includes the public pre-trained TUPA models, as they are trained on this UCCA data. It is understandable that you want to compare your current system to a baseline. We are working on a baseline model (https://github.com/cfmrp/mtool/issues/2), but unfortunately it is not ready yet.

**Comment by danielhers** [comment]
You can, however, use the sample data as you wish (it is also part of the [training data you can download under the LDC license](http://mrp.nlpl.eu/index.php?page=4)). wsj.ids and wsj.txt are available in [data/sample](data/sample), where you can also find the [sample UCCA data in MRP format](https://github.com/cfmrp/mtool/blob/master/data/sample/ucca/wsj.mrp).

**Comment by JZXXX** [comment]
@DreamerDeo I wrote scripts to get the .txt files.

**Comment by DreamerDeo** [comment]
@danielhers @JZXXX Got it! Thanks a lot for your timely response.

**Comment by JZXXX** [comment]
@DreamerDeo @danielhers Did you convert UCCA XML files which were parsed from tupa to the MRP format successfully? I find that if there is one token in a sentence that can't be anchored, this sentence will not be output. And there are lots sentences can't be anchored successfully. For example, **dev.sent_119: failed to anchor |but| in |okay, I dont have a review, but why in the hell would you name your business something that has the initials KKK....is there something behind the scenes at this place?| (26)**. I extract these sentences from the original files to get .txt files. I don't know why.
[sample.zip](https://github.com/cfmrp/mtool/files/3397439/sample.zip)

**Comment by danielhers** [comment]
@JZXXX we haven't tried converting TUPA outputs to MRP since anyway pre-trained TUPA models are not allowed to be used for system development. They were trained on older versions of the corpora, which use a different UCCA version.

**Comment by danielhers** [comment]
```
python main.py --read mrp data/sample/ucca/wsj.mrp wsj.xml --write ucca
mkdir output
cd output
csplit -zk ../wsj.xml '/^<root/' -f wsj -b '%02d.xml' {99}
cp -r ../data/sample/ucca/xml ../xml
rename 's/\.(\d)\.xml/.0$1.xml/' ../xml/*
rm -f ../xml/wsj_0002.01.xml ../xml/wsj_0003.04.xml ../xml/wsj_0007.01.xml ../xml/wsj_0012.01.xml ../xml/wsj_0012.03.xml
pip install ucca
python -m scripts.evaluate_standard . ../xml -I
>>> Average labeled F1 score: 1.000
```
