### ISSUE TITLE
EDS reduction

### ISSUE THREAD

**Issue by wangxinyu0922** [cfmrp/mtool#37]
Hi organizers,

I want to reduce EDS graph into a relatively simpler one (remove/change some redundant nodes/edges through some rules. Finally results in a DM-like graph but with more information), any suggestions about this? Maybe the rules that reducing EDS to DM is helpful (though it is a lossy reduction).

Thank you.

**Comment by oepen** [comment]
DM is, in fact, an automated conversion from EDS, first described by ivanova et al. (2012):

https://aclweb.org/anthology/papers/W/W12/W12-3602/

the code is open-source, though may be hard to extend by others.  the configuration file for the data used in the MRP 2019 context is part of the 1214 release of the ERG:

http://svn.delph-in.net/erg/tags/1214/etc/dm.cfg

going all the way to bi-lexical form, of course, requires that one throw away a fair amount of information, notably much construction semantics (that cannot just be pushed onto edges) and multiple predicates associated with the same lexical unit (e.g. the decomposition of adverbials like ‘today’).

one piece of semantics in EDS that is often discarded are most of the covert quantifiers on bare noun phrases and ‘constructionally bound’ variables, e.g. all `udef_g`, `proper_q`, and `number_q` that are not the argument of another predication (i.e. have no incoming nodes).

in principle, it could be interesting to augment `mtool` with basic graph rewriting facilities to apply various rewriting rules, but this will have to wait until after the completion of the shared task.  i believe there are various (often framework-specific) toolkits for rule-based graph rewriting out there, but i fail to have a good overview of that landscape just now.
