### ISSUE TITLE
Question about AMR data

### ISSUE THREAD

**Issue by LiuYixian** [cfmrp/mtool#44]
1. The amr data is in .mrp format, and you provide a tool to convert original amr data to mrp format. Is there a document or something like this to introduce how the conversion work? For example which nodes in original amr graph will be converted to "properties" in mrp format.

2. I see the alignments will be given with the evaluation data. Does the evaluation data mean the final test data or not? If the alignments will be given with final test data?

**Comment by oepen** [comment]
the conversion to MRP preserves the original AMR ‘as is’; the only contentful difference is that we have dropped :wiki links in the MRP training and evaluation data.

the distinction between labeled nodes (which can have any number of incoming and outgoing edges) vs. properties that are just local to one node (and have no bearing on graph topology) is native to AMR, albeit often not made explicit when visualizing AMRs.  in PenMan (Lisp-like) notation, you can tell the difference syntactically: nodes are introduced by a pair of parentheses and the ‘/’ symbol, which pairs a node identifier and its label.  property values, on the other hand, are just written as constant literals, e.g. "-" as the value of the :polarity property.

regarding your second question: yes, by evaluation data we refer to the test data for the task, and we will provide the same companion data for it: morpho-syntactic trees and JAMR and ISI alignments.
