### ISSUE TITLE
'Linkage' error when converting UCCA XML files to the MRP format

### ISSUE THREAD

**Issue by danielhers** [cfmrp/mtool#45]
When I converted UCCA XML files to the MRP format, some files succeeded, but some failed with reporting '' 'Linkage' object has no attribute 'start_position' ''. All of the files come from the English Wiki corpus (https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-Wiki), with passages being split into sentences. The converted files are: 
[test-id-sentence.zip](https://github.com/cfmrp/mtool/files/3344425/test-id-sentence.zip). I can't find the reason, thanks!

_Originally posted by @JZXXX in https://github.com/cfmrp/mtool/issues/35#issuecomment-507157434_

**Comment by danielhers** [comment]
@JZXXX note that in the official evaluation, you are not allowed to use the UCCA data from GitHub for training your model. The list of allowed resources is available on the website: http://mrp.nlpl.eu/index.php?page=4#companion
Of course you can use it during development. But the task training data should be enough: http://mrp.nlpl.eu/index.php?page=4

**Comment by JZXXX** [comment]
Thank you. We will not use extra resources for training my model, I want to make sure whether I can use these data as my development set, how about other formats?

**Comment by JZXXX** [comment]
Thank you. We will not use the unallowed extra resources for training our model, I want to make sure whether we can use these data as development set, how about other formats?

**Comment by danielhers** [comment]
Sorry, my phrasing was misleading (fixed). In fact, anything besides the whitelisted resources should not be used _for system development_ (or training). It follows you should not tune hyper-parameters on it either. This includes all formats.

**Comment by JZXXX** [comment]
OK, I know, thanks.
