### ISSUE TITLE
Checkout on windows failed due to reserved character (colon, three dots)

### ISSUE THREAD

**Issue by weissenh** [cfmrp/mtool#48]
Hi,
I tried to clone your code to my Windows computer, but the checkout failed for serveral files.
I suspect that this is probably caused by reserved characters in the file name:
- all PDFs in `score/lib` contain colons. In Windows the colon cannot be part of a file name
- the empty files with `...`  in `data/sample` were problematic too (e.g. `data/sample/amr/dot/...`, `data/sample/amr/pdf/...`, `data/sample/dm/dot/...`, etc.  )

I guess that there are some ugly workarounds, but changing the mentioned file names seems to be one small step for a (wo)man, but one giant leap for Windows users ;-)
Would it be possible to change the filenames of the respective files such that they are no longer illegal according to Windows? (e.g. replacing the error-causing characters by underscores?)

**Comment by oepen** [comment]
thanks for your problem report!  we shall look into cross-platform file naming conventions, though it might take a few days just now before we can update the repository.

neither of the directories causing you problems are required for running the tool, so i hope you will find a way to work around these issues for now?  e.g. instruct your git client to skip these directories, or get a copy of the repository on a non-windows machine and transfer locally.

**Comment by weissenh** [comment]
First of all thanks for your answer!
I can just ignore the errors for now, but it's kind annoying, that's why I opened the issue and that's why I'm looking forward to the filename changes.

**Comment by oepen** [comment]
please see whether things are better on Windows now?!
