### ISSUE TITLE
Faster smatch?

### ISSUE THREAD

**Issue by namednil** [cfmrp/mtool#53]
Did you consider making use of the considerably faster smatch [re-implementation by Liu et al.](https://github.com/Oneplus/tamr/tree/master/amr_aligner/smatch)?

**Comment by oepen** [comment]
truth be told, i at least was not aware of this re-implementation.  our guiding principle regarding SMATCH has been to stick to the 'official' version, as linked from the ISI web pages for AMR.  in my view, even minor variation in how different implementations of the 'same' metric compute results is undesirable ... there should be no uncertainty in evaluation :-).

please see my comments on #52 regarding our current thinking about making further revisions to the MRP scorer.  i think i will just keep this ticket open for the time being ...
