### ISSUE TITLE
Too slow of the scorer

### ISSUE THREAD

**Issue by bcmi220** [cfmrp/mtool#55]
The scorer is a little bit too slow, do you have any ideas to make this faster?

**Comment by oepen** [comment]
as of today, the ‘dev’ branch supports multi-processing, i.e. on a machine with multiple cpu cores it will parallelize the MRP scoring.  please consider switching to this branch (e.g. `git checkout dev`, from within the `mtool` directory) and try giving it a suitable `--cores` value, say `4` or `24`, depending on your available hardware.  also, the ‘dev’ branch includes some code optimizations (courtesy of @taryou), which by themselves can make it run up to two times faster, even without parallelization.

we will likely promote the current ‘dev’ branch to official status for the MRP scorer sometime this coming week, but as the shared task is moving into its critical phases we want to complete more testing of the revised code and, thus, would be grateful if at least some participants could be part of that quality assurance already :-).
