### ISSUE TITLE
Can we get the source of frames in SDP?

### ISSUE THREAD

**Issue by JZXXX** [cfmrp/mtool#57]
We want to know the meaning of frame values, but we can't find the specific explanation. I wonder where we can find these information.

**Comment by hajic** [comment]
For short descriptions of the "functors", see https://ufal.mff.cuni.cz/pdt2.0/doc/manuals/en/t-layer/html/ch07.html

**Comment by oepen** [comment]
for the PSD graphs, the ‘frame’ values really are straight sense identifiers into the PCEDT valence dictionary, [CzEngVallex](http://hdl.handle.net/11234/1-1512); these apply (near-)exclusively to verbal nodes.

for DM, (nearly) all content words carry ‘frame’ values, but these are not quite as thoroughly documented as the PSD inventory.  they are comprised of two colon-separated fields, of which the first further differentiates the semantic predicate beyond its lemma, e.g. for verb–particle constructions (‘look at something’ vs. ‘look up something’: ‘v’ vs. ‘v_up’), causative vs. inchoative verbs (‘something increased’ vs. ‘someone increased something’: ‘v’ vs. ‘v_cause’), or main vs. modal verbs (‘have something’ vs. ‘have to do something’: ‘v’ vs. ‘v_qmodal’).  the second field is essentially the (possible) valency of the predicate, in coarse semantic types, i.e. a sequence of one-character type indicators that would correspond to the ARG0 .. ARGn semantics arguments in a complete usage.  a bit like for PSD, there is a lexicon of all possible predicates (in the full semantics from which DM is derived), which we have included in the white-list of legitimate resources:

+ ERG SEM-I: http://svn.delph-in.net/erg/tags/1214/etc

personally, i am not sure participants really need to wholly dig into this space; in past SDP tasks, frame prediction oftentimes was approached with good success as a token-level classification task (possibly informed by the semantic dependency graph).  but for anyone wanting to read these representations more closely, the following might be a good starting page regarding predicate naming in DM (and EDS):

http://moin.delph-in.net/ErgSemantics/Essence#ArgumentIdentification
