### ISSUE TITLE
Question about the evaluation output format

### ISSUE THREAD

**Issue by bcmi220** [cfmrp/mtool#59]
Dear organizer, I am preparing for the evaluation submission, but the output format in the instruction is not very clear. "all parser outputs to be submitted must be concatenated into a single MRP file (for example output.mrp)", can you give an example of the output.mrp? Thanks.

**Comment by oepen** [comment]
any valid MRP file should work for the CodaLab submission site.  essentially, you need to make sure that parser outputs are properly serialized in the MRP JSON Lines format, one per line.  for upload to CodaLab, you will then have to compress the MRP file into a ZIP archive.  our sample package of WSJ graphs in all frameworks also contains example `input.mrp` and `output.mrp` files.  please see:

http://svn.nlpl.eu/mrp/2019/public/sample/README.txt
http://svn.nlpl.eu/mrp/2019/public/sample.tgz
