### ISSUE TITLE
basic validation

### ISSUE THREAD

**Issue by oepen** [cfmrp/mtool#6]
we still need to provide a validator for MRP graphs to participants.  beyond making sure that a file can be parsed in the MRP file format, how far should we push notions of wellformedness?  for example:

+ existence of the ‘source’ and ‘target’ nodes on edges?
+ validity of top-level ‘flavor’ and ‘framework’ fields?
+ type constraints, e.g. all node identifiers are integers?
+ well-formedness of ‘anchors’ (all frameworks but AMR)?
+ presence of node (except UCCA) and edge labels?

**Comment by oepen** [comment]
for AMR graphs, in case a parser predicts inverted edges, it should be expected to explicitly mark them using the ‘normal’ property.

**Comment by oepen** [comment]
i have now created the outline of a validation ‘infrastructure’ and would invite others to contribute, in particular to the framework-specific parts (including creating ill-formed test cases :-).  for example:
```
./main.py --n 1 --read mrp --validate all data/validate/eds/wsj.mrp 
validate(): graph ‘20001001’: missing or invalid ‘input’ property
validate(): graph ‘20001001’; node #0: missing or invalid label
validate(): graph ‘20001001’; node #1: missing or invalid label
validate(): graph ‘20001001’; node #3: missing or invalid anchoring
validate(): graph ‘20001001’; node #6: invalid ‘anchors’ value: [{'from': 15, 'to': 23}, {'from': 15, 'to': 23}]
validate(): graph ‘20001001’; node #7: invalid ‘anchors’ value: [{'form': 15, 'to': 17}]
```

**Comment by danielhers** [comment]
Should it also check for less severe issues that technically do not hinder evaluation (but will get penalized in the score)? For UCCA we could also check:

- [x] Each node has exactly one primary parent, except the root, which has none
- [x] The root has no remote parents either
- [x] Every node is anchored or has an anchored primary descendent
- [ ] No cycles
- [x] Edge labels are in `{A, C, D, E, F, G, H, L, N, P, Q, R, S, T}`

**Comment by oepen** [comment]
sorry, i see i never replied to this thread earlier!

in principle, i think more diagnostics will always be good.  i too had meant to give a little more thought to what framework-specific tests could be applied (for DM and EDS), but at this point i have no strong ambitions to get this done before the end of the evaluation period.

i did just extend the validation 'infrastructure' to distinguish errors (the default) from warnings, as well as to optionally flag framework-specific messages.  for example:
```
./main.py --read mrp --validate all data/validate/eds/wsj.mrp 
validate(): [E] graph #20001001: missing or invalid ‘input’ property
validate(): [E] {EDS} graph #20001001; node #0: missing or invalid label
validate(): [E] {EDS} graph #20001001; node #1: missing or invalid label
validate(): [E] {EDS} graph #20001001; node #3: missing or invalid anchoring
validate(): [E] {EDS} graph #20001001; node #6: invalid ‘anchors’ value: [{'from': 15, 'to': 23}, {'from': 15, 'to': 23}]
validate(): [E] {EDS} graph #20001001; node #7: invalid ‘anchors’ value: [{'form': 15, 'to': 17}]
validate(): [E] graph #20001002: missing or invalid ‘flavor’ property
validate(): [E] graph #20003001: invalid Flavor (0) framework: eds
validate(): [E] graph #20003002: missing or invalid ‘flavor’ property
validate(): [E] graph #20003002: missing or invalid ‘framework’ property
```
