### ISSUE TITLE
The Codalab competition website is unavailable

### ISSUE THREAD

**Issue by bcmi220** [cfmrp/mtool#63]
Dear organizer,
The Codalab competition website is unavailable for several days, do you know when it will be recovered?

**Comment by danielhers** [comment]
Following a Codalab server malfunction, we are working with the Codalab team to re-create the competition on a replacement server. We expect it to be available again by Monday, July 15.

**Comment by oepen** [comment]
CodaLab is back in business, and the MRP 2019 registration and submission interface available again.
