### ISSUE TITLE
The release of whole set of the evaluation graphs in shared task

### ISSUE THREAD

**Issue by DreamerDeo** [cfmrp/mtool#68]
Hi,  I notice that only the sub-set of the evaluation graphs (named lpps) has released in MRP website on August 9, 2019. Is there any plan to release the whole set of the evaluation graphs? By this way, we could test our follow-up research work on this data.

Thank you for organizing this interesting shared task! We have learned a lot through this.

**Comment by oepen** [comment]
we are discussing the possibility of re-running the MRP shared task in 2020, hence have opted to be a bit protective of the full evaluation data for the time being.

please see the archives in the ‘mrp-participants’ mailing list for the possibility of having (a limited number of) additional, post-evaluation submissions scored by us.
