### ISSUE TITLE
Mismatch in UCCA remote edge data format

### ISSUE THREAD

**Issue by DreamerDeo** [cfmrp/mtool#70]
In CoNLL2019 dataset, the remote edge was tagged with `Edge Properties` and set it value as `true` , while it was called `Edge Attributes` in [mrp-website](http://mrp.nlpl.eu/index.php?page=5). However, when I try to convert the UCCA_English-Wiki dataset into mrp format using mtool. I find the remote edge was tagged with `Edge Attributes`.

That is to say, there is a format mismatch in remote edge data format.

This might due to lines 92~94 in mtool/ucca.py .
```
attributes, values = None, None;
if edge.attrib.get("remote"):
attributes = ["remote"];
values = [True];
```

**Comment by danielhers** [comment]
Hi @DreamerDeo,
the latest format specifies edge have *attributes* while nodes have *properties*, to make a clearer distinction. While older data specifies edge properties, `mtool` reads them as edge attributes when decoding the json: https://github.com/cfmrp/mtool/blob/master/graph.py#L336

**Comment by DreamerDeo** [comment]
@danielhers Got it, thank u!
