### ISSUE TITLE
mtool enters an infinite loop when converting from mrp to ucca

### ISSUE THREAD

**Issue by lovodkin93** [cfmrp/mtool#86]
Hello,
I am working on a project involving an conversion between mrp files representing ucca graphs and xml files.
I am trying to run the conversion script (`python3 main.py --read mrp --write ucca /path/to/mrp_file /path/to/xml_file`), and it appears the script enters an inifinite loop around the while loop in [while loop](https://github.com/cfmrp/mtool/blob/master/codec/ucca.py#L165).
I have tried to understand its origin, but in vain.
has anyone ever encountered such a problem?
I have also attached the mrp file in question (in json mode).
[prediction_ucca_eng_424.json.tar.gz](https://github.com/cfmrp/mtool/files/6826609/prediction_ucca_eng_424.json.tar.gz)

thanks!

**Comment by danielhers** [comment]
Hi Aviv, this would happen if there is a cycle in the graph, I think. An easy way to avoid it is to only do these two lines if it is not already in id_to_unit: https://github.com/cfmrp/mtool/blob/4cee3a2590d4ec7648408cede05adfaeccc0c698/codec/ucca.py#L174-L175

**Comment by lovodkin93** [comment]
I figured it occurs due to a cycle in the graph, but I couldn't understand how to avoid it.
Great, I will give it a go!
p.s by "**it** is not already in id_to_unit", you refer to `child_unit`, right?

**Comment by danielhers** [comment]
Yes.
