### ISSUE TITLE
Conversion from camr to mrp without anchors

### ISSUE THREAD

**Issue by Lmxiao4** [cfmrp/mtool#88]
This is a camr file. 
<img width="643" alt="1650872303(1)" src="https://user-images.githubusercontent.com/86300641/165043681-1641f64a-2f1e-4fd7-9d91-39c09e10466e.png">
I want to convert it into mrp file with following command:
./main.py --read camr --write mrp data/sample/camr/gold.txt data/sample/camr/gold.mrp
However, the nodes dict in output file doesn't have anchors. What command should I use?

**Comment by danielhers** [comment]
You must specify the `--text` argument for anchors. See here: https://github.com/cfmrp/mtool#conversion

**Comment by Lmxiao4** [comment]
Thanks!
